var rule={
    title:'看影网',
    host:'https://www.kanying.me',
    url:'/so/fyclass/-------fypage---/',
    searchUrl:'/search/**----------fypage---/',
    searchable:1,quickSearch:1,play_parse:true,limit:6,
    headers:{'User-Agent':'MOBILE_UA'},
class_name: '电影&剧集&综艺&动漫',
class_url: '1&2&3&4',
   tab_exclude: '同类型|同主演|同TAG',
    lazy:'',
    推荐:'*',
    一级:'.myui-vodlist li;a&&title;.lazyload&&data-original;.pic-text&&Text;a&&href',
    二级:{title:'h1&&Text',
    img:'.lazyload&&src',
    desc:'.text-muted:eq(-1)&&Text;.text-muted:eq(-5)&&Text;.myui-content__detail p:eq(4)&&Text;.myui-content__detail p:eq(5)&&Text;.myui-content__detail p:eq(6)&&Text',
    content:'.content&&Text',
    tabs:'.nav.nav-tabs a',
    lists:'.myui-content__list:eq(#id) li'},
    搜索:'.myui-vodlist__media li;a&&title;*;*;a&&href;.detail&&p:eq(2)&&Text',
}